import json,sys,re,html
J=json.load(open(sys.argv[1]))
pages={'ripples':'watson-hartsoe-site/ripples-conference-presentation-rebuilt.html','lego':'watson-hartsoe-site/can_a_language_model_build_with_lego__2_.html',
 'playfreedom':'watson-hartsoe-site/play-freedom-ai-films-tufte_5_.html','ekphrasis':'watson-hartsoe-site/operative-ekphrasis-relational-essay.html','pronoun':'watson-hartsoe-site/the-pronoun-alibi.html'}
shot={'ripples':'ripples','lego':'lego','playfreedom':'playfreedom','ekphrasis':'ekphrasis','pronoun':'pronoun'}
fj=open('cartoon/films.js').read().rstrip()
cut=fj.find('\n/* ---------- New figures, drawn as films')
if cut>-1: fj=fj[:cut]
else: fj=fj[:fj.rfind('})();')].rstrip()
add='\n/* ---------- New figures, drawn as films (generated by tools/films2.py; the SVG is in each page) ---------- */\n'
for k,v in J.items():
    add+='/* %s · %s */\nF[%s]=%s;\n'%(pages[k].split('/')[-1],html.unescape(v['cap']).split('. ',1)[1][:90],json.dumps(v['id']),json.dumps(v['spec'],ensure_ascii=False,separators=(',',':')))
    p=pages[k];s=open(p).read()
    fig=('<figure class="df-fig" style="margin:1.6rem auto 2rem;max-width:min(960px,calc(100vw - 32px))"><div class="df-frame" style="border:1.5px solid #141412;border-radius:6px;overflow:hidden">'
         +v['svg']+'</div><figcaption style="margin:.45rem 0 0;font:500 .82rem/1.45 ui-sans-serif,-apple-system,Segoe UI,Arial,sans-serif;color:#3a382f">'+v['cap']+'</figcaption></figure>')
    old=re.search(r'<figure class="mp-shot" data-shot="%s"[^>]*></figure>|<figure class="df-fig".*?</figure>'%shot[k],s,re.S)
    assert old,(k,p)
    s=s[:old.start()]+fig+s[old.end():]
    s=s.replace('<script src="../cartoon/shots.js" defer></script><script src="../cartoon/cartoon.js" defer></script>','<script src="../cartoon/cartoon.js" defer></script><script src="../cartoon/films.js" defer></script><script src="../cartoon/dfilm.js" defer></script>')
    assert 'dfilm.js' in s,p
    open(p,'w').write(s)
fj=fj+'\n'+add+'})();\n'
open('cartoon/films.js','w').write(fj)
print('ok')
